import { DATABASE } from "./database.js";
import { Benelux } from "./data/Benelux.js";
import { Central_European } from "./data/Central_European.js";
import { French } from "./data/French.js";
import { German_Austrian } from "./data/German_Austrian.js";
import { Iberian } from "./data/Iberian.js";
import { Italian } from "./data/Italian.js";
import { Nordic } from "./data/Nordic.js";
import { Brazilian } from "./data/Brazilian.js";
import { North_American } from "./data/North_American.js";
import { Balkan } from "./data/Balkan.js";
import { Irish } from "./data/Irish.js";
import { Pacific } from "./data/Pacific.js";

export const LEAGUES = [
  {
    id: "BR",
    name: "Liga Británica e Irlandesa",
    description: "13 clubes de Gran Bretaña e Irlanda.",
    cupName: "Copa de Gran Bretaña e Irlanda",
    cupShortName: "Copa de Gran Bretaña",
    leagueTitlesLabel: "Ligas de Gran Bretaña e Irlanda",
    cupTitlesLabel: "Copas de Gran Bretaña e Irlanda",
    Teams: DATABASE.Teams,
    Players: DATABASE.Players,
    TransferMarket: DATABASE.TransferMarket,
  },
  {
    id: "IB",
    name: "Liga de la Península Ibérica",
    description: "14 clubes de España y Portugal.",
    cupName: "Copa Ibérica",
    cupShortName: "Copa Ibérica",
    leagueTitlesLabel: "Ligas de la Península Ibérica",
    cupTitlesLabel: "Copas de la Península Ibérica",
    euroSpots: 4,
    Teams: Iberian.Teams,
    Players: Iberian.Players,
    TransferMarket: Iberian.TransferMarket,
  },
  {
    id: "FR",
    name: "Liga Francesa de Quidditch",
    description: "14 clubes de Francia.",
    cupName: "Coupe de France de Quidditch",
    cupShortName: "Copa de Francia",
    leagueTitlesLabel: "Ligas de Francia",
    cupTitlesLabel: "Copas de Francia",
    Teams: French.Teams,
    Players: French.Players,
    TransferMarket: French.TransferMarket,
  },
  {
    id: "DE",
    name: "Liga Germano Austriaca",
    description: "14 clubes de Alemania y Austria.",
    cupName: "Copa Germano Austriaca",
    cupShortName: "Copa Germano Austriaca",
    leagueTitlesLabel: "Ligas de Alemania y Austria",
    cupTitlesLabel: "Copas de Alemania y Austria",
    Teams: German_Austrian.Teams,
    Players: German_Austrian.Players,
    TransferMarket: German_Austrian.TransferMarket,
  },
  {
    id: "IT",
    name: "Lega Italiana di Quidditch",
    description: "14 clubes de Italia.",
    cupName: "Coppa Italia di Quidditch",
    cupShortName: "Copa de Italia",
    leagueTitlesLabel: "Ligas de Italia",
    cupTitlesLabel: "Copas de Italia",
    Teams: Italian.Teams,
    Players: Italian.Players,
    TransferMarket: Italian.TransferMarket,
  },
  {
    id: "BE",
    name: "Liga de Quidditch del Benelux",
    description: "12 clubes de Bélgica, Países Bajos y Luxemburgo.",
    cupName: "Copa del Benelux",
    cupShortName: "Copa del Benelux",
    leagueTitlesLabel: "Ligas del Benelux",
    cupTitlesLabel: "Copas del Benelux",
    Teams: Benelux.Teams,
    Players: Benelux.Players,
    TransferMarket: Benelux.TransferMarket,
  },
  {
    id: "CE",
    name: "Liga Centroeuropea",
    description: "14 clubes de Polonia, Chequia, Hungría y Eslovaquia.",
    cupName: "Copa Centroeuropea",
    cupShortName: "Copa Centroeuropea",
    leagueTitlesLabel: "Ligas de Europa Central",
    cupTitlesLabel: "Copas de Europa Central",
    Teams: Central_European.Teams,
    Players: Central_European.Players,
    TransferMarket: Central_European.TransferMarket,
  },
  {
    id: "NO",
    name: "Nordic Quidditch League",
    description: "14 clubes de Suecia, Dinamarca, Noruega, Finlandia e Islandia.",
    cupName: "Copa Nórdica",
    cupShortName: "Copa Nórdica",
    leagueTitlesLabel: "Ligas Nórdicas",
    cupTitlesLabel: "Copas Nórdicas",
    Teams: Nordic.Teams,
    Players: Nordic.Players,
    TransferMarket: Nordic.TransferMarket,
  },
  {
    id: "BRZ",
    name: "Liga Brasileña de Quidditch",
    description: "14 clubes de Brasil.",
    european: false,
    cupName: "Copa de Brasil",
    cupShortName: "Copa de Brasil",
    leagueTitlesLabel: "Ligas de Brasil",
    cupTitlesLabel: "Copas de Brasil",
    Teams: Brazilian.Teams,
    Players: Brazilian.Players,
    TransferMarket: Brazilian.TransferMarket,
  },
  {
    id: "NA",
    name: "Liga de Quidditch de EE. UU. y Canadá",
    description: "14 clubes de Estados Unidos y Canadá.",
    european: false,
    cupName: "Copa Norteamericana",
    cupShortName: "Copa Norteamericana",
    leagueTitlesLabel: "Ligas de Norteamérica",
    cupTitlesLabel: "Copas de Norteamérica",
    Teams: North_American.Teams,
    Players: North_American.Players,
    TransferMarket: North_American.TransferMarket,
  },
  {
    id: "BA",
    name: "Liga de Quidditch de los Balcanes",
    description: "15 clubes de los Balcanes.",
    cupName: "Copa de los Balcanes",
    cupShortName: "Copa de los Balcanes",
    leagueTitlesLabel: "Ligas de los Balcanes",
    cupTitlesLabel: "Copas de los Balcanes",
    euroSpots: 3,
    Teams: Balkan.Teams,
    Players: Balkan.Players,
    TransferMarket: Balkan.TransferMarket,
  },
  {
    id: "IE",
    name: "Liga Irlandesa de Quidditch",
    description: "14 clubes de Irlanda.",
    cupName: "Copa de Irlanda",
    cupShortName: "Copa de Irlanda",
    leagueTitlesLabel: "Ligas de Irlanda",
    cupTitlesLabel: "Copas de Irlanda",
    Teams: Irish.Teams,
    Players: Irish.Players,
    TransferMarket: Irish.TransferMarket,
  },
  {
    id: "PC",
    name: "Pacific Quidditch League",
    description: "14 clubes de Australia, Nueva Zelanda y Japón.",
    european: false,
    cupName: "Copa del Pacífico",
    cupShortName: "Copa del Pacífico",
    leagueTitlesLabel: "Ligas del Pacífico",
    cupTitlesLabel: "Copas del Pacífico",
    Teams: Pacific.Teams,
    Players: Pacific.Players,
    TransferMarket: Pacific.TransferMarket,
  },
];

export function leagueById(leagueId) {
  return LEAGUES.find((league) => league.id === leagueId) || LEAGUES[0];
}