export const DATABASE = {
  "Teams": [
    {
      "TeamID": "T01",
      "Name": "Montrose Magpies",
      "Country": "Scotland",
      "OVR": 94,
      "Budget(G)": 470000,
      "ReputationStars": 5,
      "LeagueTitles": 32,
      "TeamOVR(Auto)": 93.1
    },
    {
      "TeamID": "T02",
      "Name": "Ballycastle Bats",
      "Country": "Northern Ireland",
      "OVR": 92,
      "Budget(G)": 460000,
      "ReputationStars": 4,
      "LeagueTitles": 27,
      "TeamOVR(Auto)": 91.3
    },
    {
      "TeamID": "T03",
      "Name": "Puddlemere United",
      "Country": "England",
      "OVR": 91,
      "Budget(G)": 455000,
      "ReputationStars": 4,
      "LeagueTitles": 22,
      "TeamOVR(Auto)": 87.6
    },
    {
      "TeamID": "T04",
      "Name": "Chudley Cannons",
      "Country": "England",
      "OVR": 89,
      "Budget(G)": 445000,
      "ReputationStars": 4,
      "LeagueTitles": 21,
      "TeamOVR(Auto)": 88
    },
    {
      "TeamID": "T05",
      "Name": "Caerphilly Catapults",
      "Country": "Wales",
      "OVR": 88,
      "Budget(G)": 440000,
      "ReputationStars": 4,
      "LeagueTitles": 18,
      "TeamOVR(Auto)": 87.4
    },
    {
      "TeamID": "T06",
      "Name": "Wimbourne Wasps",
      "Country": "England",
      "OVR": 87,
      "Budget(G)": 435000,
      "ReputationStars": 3,
      "LeagueTitles": 18,
      "TeamOVR(Auto)": 84.1
    },
    {
      "TeamID": "T07",
      "Name": "Tutshill Tornados",
      "Country": "England",
      "OVR": 86,
      "Budget(G)": 430000,
      "ReputationStars": 3,
      "LeagueTitles": 5,
      "TeamOVR(Auto)": 83.4
    },
    {
      "TeamID": "T08",
      "Name": "Holyhead Harpies",
      "Country": "Wales",
      "OVR": 85,
      "Budget(G)": 425000,
      "ReputationStars": 3,
      "LeagueTitles": 10,
      "TeamOVR(Auto)": 82.9
    },
    {
      "TeamID": "T09",
      "Name": "Falmouth Falcons",
      "Country": "England",
      "OVR": 84,
      "Budget(G)": 420000,
      "ReputationStars": 3,
      "LeagueTitles": 14,
      "TeamOVR(Auto)": 81.7
    },
    {
      "TeamID": "T10",
      "Name": "Appleby Arrows",
      "Country": "England",
      "OVR": 83,
      "Budget(G)": 415000,
      "ReputationStars": 3,
      "LeagueTitles": 12,
      "TeamOVR(Auto)": 81
    },
    {
      "TeamID": "T11",
      "Name": "Kenmare Kestrels",
      "Country": "Ireland",
      "OVR": 82,
      "Budget(G)": 410000,
      "ReputationStars": 2,
      "LeagueTitles": 9,
      "TeamOVR(Auto)": 79.7
    },
    {
      "TeamID": "T12",
      "Name": "Wigtown Wanderers",
      "Country": "Scotland",
      "OVR": 80,
      "Budget(G)": 400000,
      "ReputationStars": 2,
      "LeagueTitles": 7,
      "TeamOVR(Auto)": 78.6
    },
    {
      "TeamID": "T13",
      "Name": "Pride of Portree",
      "Country": "Scotland",
      "OVR": 78,
      "Budget(G)": 390000,
      "ReputationStars": 2,
      "LeagueTitles": 2,
      "TeamOVR(Auto)": 74.7
    }
  ],
  "Players": [
    {
      "PlayerID": "P001",
      "TeamID": "T01",
      "Name": "Aled Griffin",
      "Position": "Chaser",
      "OVR": 92,
      "Age": 31,
      "Nationality": "Scotland",
      "Value(G)": 14112,
      "Salary(G/week)": 117,
      "ContractYears": 3,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 91,
      "Attribute2": "ShotAccuracy",
      "Value2": 95,
      "ReleaseClause(G)": 28365,
      "Morale": 73,
      "Form": 67,
      "Injured": "No"
    },
    {
      "PlayerID": "P002",
      "TeamID": "T01",
      "Name": "Edwin Ravens",
      "Position": "Chaser",
      "OVR": 88,
      "Age": 32,
      "Nationality": "Scotland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 3,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 89,
      "Attribute2": "ShotAccuracy",
      "Value2": 86,
      "ReleaseClause(G)": 26223,
      "Morale": 83,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P003",
      "TeamID": "T01",
      "Name": "Sean Byrne",
      "Position": "Chaser",
      "OVR": 94,
      "Age": 30,
      "Nationality": "Scotland",
      "Value(G)": 15488,
      "Salary(G/week)": 129,
      "ContractYears": 2,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 96,
      "Attribute2": "ShotAccuracy",
      "Value2": 92,
      "ReleaseClause(G)": 39339,
      "Morale": 94,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P004",
      "TeamID": "T01",
      "Name": "Ansel Blackwood",
      "Position": "Beater",
      "OVR": 96,
      "Age": 23,
      "Nationality": "England",
      "Value(G)": 16928,
      "Salary(G/week)": 141,
      "ContractYears": 2,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 99,
      "Attribute2": "BatAccuracy",
      "Value2": 96,
      "ReleaseClause(G)": 39950,
      "Morale": 82,
      "Form": 83,
      "Injured": "No"
    },
    {
      "PlayerID": "P005",
      "TeamID": "T01",
      "Name": "Liam Baker",
      "Position": "Beater",
      "OVR": 90,
      "Age": 19,
      "Nationality": "Scotland",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 3,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 90,
      "Attribute2": "BatAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 28160,
      "Morale": 78,
      "Form": 65,
      "Injured": "No"
    },
    {
      "PlayerID": "P006",
      "TeamID": "T01",
      "Name": "Yorick Locke",
      "Position": "Keeper",
      "OVR": 96,
      "Age": 25,
      "Nationality": "Scotland",
      "Value(G)": 16928,
      "Salary(G/week)": 141,
      "ContractYears": 1,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 98,
      "Attribute2": "Saving",
      "Value2": 93,
      "ReleaseClause(G)": 39950,
      "Morale": 96,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P007",
      "TeamID": "T01",
      "Name": "Ewan Pryce",
      "Position": "Seeker",
      "OVR": 96,
      "Age": 28,
      "Nationality": "Scotland",
      "Value(G)": 16928,
      "Salary(G/week)": 141,
      "ContractYears": 5,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 95,
      "Attribute2": "Agility",
      "Value2": 95,
      "ReleaseClause(G)": 38765,
      "Morale": 94,
      "Form": 65,
      "Injured": "No"
    },
    {
      "PlayerID": "P008",
      "TeamID": "T01",
      "Name": "Fraser Marlowe",
      "Position": "Reserve",
      "OVR": 88,
      "Age": 22,
      "Nationality": "Scotland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 2,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 20447,
      "Morale": 77,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P009",
      "TeamID": "T01",
      "Name": "Bran McBride",
      "Position": "Reserve",
      "OVR": 92,
      "Age": 31,
      "Nationality": "Scotland",
      "Value(G)": 14112,
      "Salary(G/week)": 117,
      "ContractYears": 1,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 89,
      "Attribute2": "ShotAccuracy",
      "Value2": 95,
      "ReleaseClause(G)": 33022,
      "Morale": 97,
      "Form": 82,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P010",
      "TeamID": "T01",
      "Name": "Callum Blackwood",
      "Position": "Reserve",
      "OVR": 88,
      "Age": 24,
      "Nationality": "Scotland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 1,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 25067,
      "Morale": 83,
      "Form": 95,
      "Injured": "No"
    },
    {
      "PlayerID": "P011",
      "TeamID": "T02",
      "Name": "Eoin Boyd",
      "Position": "Chaser",
      "OVR": 93,
      "Age": 29,
      "Nationality": "Northern Ireland",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 2,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 95,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 28548,
      "Morale": 93,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P012",
      "TeamID": "T02",
      "Name": "Dorian Sterling",
      "Position": "Chaser",
      "OVR": 93,
      "Age": 20,
      "Nationality": "Northern Ireland",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 5,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 90,
      "Attribute2": "ShotAccuracy",
      "Value2": 96,
      "ReleaseClause(G)": 26329,
      "Morale": 79,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P013",
      "TeamID": "T02",
      "Name": "Hamish Davies",
      "Position": "Chaser",
      "OVR": 91,
      "Age": 26,
      "Nationality": "England",
      "Value(G)": 13448,
      "Salary(G/week)": 112,
      "ContractYears": 3,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 92,
      "ReleaseClause(G)": 33888,
      "Morale": 88,
      "Form": 93,
      "Injured": "No"
    },
    {
      "PlayerID": "P014",
      "TeamID": "T02",
      "Name": "Owain Evans",
      "Position": "Beater",
      "OVR": 88,
      "Age": 20,
      "Nationality": "Northern Ireland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 1,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 89,
      "Attribute2": "BatAccuracy",
      "Value2": 86,
      "ReleaseClause(G)": 27031,
      "Morale": 97,
      "Form": 83,
      "Injured": "No"
    },
    {
      "PlayerID": "P015",
      "TeamID": "T02",
      "Name": "Zane Boyd",
      "Position": "Beater",
      "OVR": 90,
      "Age": 22,
      "Nationality": "Northern Ireland",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 5,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 87,
      "Attribute2": "BatAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 31232,
      "Morale": 91,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P016",
      "TeamID": "T02",
      "Name": "Dafydd Crawley",
      "Position": "Keeper",
      "OVR": 93,
      "Age": 23,
      "Nationality": "Northern Ireland",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 4,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 96,
      "Attribute2": "Saving",
      "Value2": 93,
      "ReleaseClause(G)": 33577,
      "Morale": 81,
      "Form": 80,
      "Injured": "No"
    },
    {
      "PlayerID": "P017",
      "TeamID": "T02",
      "Name": "Alasdair Evans",
      "Position": "Seeker",
      "OVR": 91,
      "Age": 29,
      "Nationality": "Northern Ireland",
      "Value(G)": 13448,
      "Salary(G/week)": 112,
      "ContractYears": 1,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "Agility",
      "Value2": 92,
      "ReleaseClause(G)": 24071,
      "Morale": 75,
      "Form": 87,
      "Injured": "No"
    },
    {
      "PlayerID": "P018",
      "TeamID": "T02",
      "Name": "Fraser Dawson",
      "Position": "Reserve",
      "OVR": 86,
      "Age": 29,
      "Nationality": "Northern Ireland",
      "Value(G)": 10368,
      "Salary(G/week)": 86,
      "ContractYears": 3,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 19491,
      "Morale": 79,
      "Form": 92,
      "Injured": "No"
    },
    {
      "PlayerID": "P019",
      "TeamID": "T02",
      "Name": "Zane Ellis",
      "Position": "Reserve",
      "OVR": 90,
      "Age": 27,
      "Nationality": "Northern Ireland",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 1,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 30464,
      "Morale": 84,
      "Form": 90,
      "Injured": "No"
    },
    {
      "PlayerID": "P020",
      "TeamID": "T02",
      "Name": "Wyatt Grant",
      "Position": "Reserve",
      "OVR": 93,
      "Age": 36,
      "Nationality": "Northern Ireland",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 2,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 91,
      "Attribute2": "ShotAccuracy",
      "Value2": 94,
      "ReleaseClause(G)": 36980,
      "Morale": 84,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P021",
      "TeamID": "T03",
      "Name": "Dorian Pryce",
      "Position": "Chaser",
      "OVR": 89,
      "Age": 21,
      "Nationality": "England",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 2,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 91,
      "Attribute2": "ShotAccuracy",
      "Value2": 89,
      "ReleaseClause(G)": 30298,
      "Morale": 88,
      "Form": 93,
      "Injured": "No"
    },
    {
      "PlayerID": "P022",
      "TeamID": "T03",
      "Name": "Ansel York",
      "Position": "Chaser",
      "OVR": 86,
      "Age": 19,
      "Nationality": "England",
      "Value(G)": 10368,
      "Salary(G/week)": 86,
      "ContractYears": 5,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 85,
      "Attribute2": "ShotAccuracy",
      "Value2": 84,
      "ReleaseClause(G)": 24468,
      "Morale": 80,
      "Form": 67,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P023",
      "TeamID": "T03",
      "Name": "Xander Ravens",
      "Position": "Chaser",
      "OVR": 87,
      "Age": 30,
      "Nationality": "England",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 1,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 90,
      "Attribute2": "ShotAccuracy",
      "Value2": 90,
      "ReleaseClause(G)": 19604,
      "Morale": 97,
      "Form": 91,
      "Injured": "No"
    },
    {
      "PlayerID": "P024",
      "TeamID": "T03",
      "Name": "Silas Munro",
      "Position": "Beater",
      "OVR": 87,
      "Age": 32,
      "Nationality": "Ireland",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 2,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 88,
      "Attribute2": "BatAccuracy",
      "Value2": 84,
      "ReleaseClause(G)": 21356,
      "Morale": 86,
      "Form": 93,
      "Injured": "No"
    },
    {
      "PlayerID": "P025",
      "TeamID": "T03",
      "Name": "Kieran Fairchild",
      "Position": "Beater",
      "OVR": 87,
      "Age": 27,
      "Nationality": "England",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 5,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 89,
      "Attribute2": "BatAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 21356,
      "Morale": 75,
      "Form": 95,
      "Injured": "No"
    },
    {
      "PlayerID": "P026",
      "TeamID": "T03",
      "Name": "Niall McBride",
      "Position": "Keeper",
      "OVR": 85,
      "Age": 19,
      "Nationality": "Northern Ireland",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 1,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 83,
      "Attribute2": "Saving",
      "Value2": 85,
      "ReleaseClause(G)": 20384,
      "Morale": 99,
      "Form": 86,
      "Injured": "No"
    },
    {
      "PlayerID": "P027",
      "TeamID": "T03",
      "Name": "Conor Campbell",
      "Position": "Seeker",
      "OVR": 92,
      "Age": 20,
      "Nationality": "England",
      "Value(G)": 14112,
      "Salary(G/week)": 117,
      "ContractYears": 1,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 92,
      "Attribute2": "Agility",
      "Value2": 94,
      "ReleaseClause(G)": 29494,
      "Morale": 90,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P028",
      "TeamID": "T03",
      "Name": "Darragh Byrne",
      "Position": "Reserve",
      "OVR": 86,
      "Age": 20,
      "Nationality": "England",
      "Value(G)": 10368,
      "Salary(G/week)": 86,
      "ContractYears": 3,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 23431,
      "Morale": 96,
      "Form": 74,
      "Injured": "No"
    },
    {
      "PlayerID": "P029",
      "TeamID": "T03",
      "Name": "Bran Murphy",
      "Position": "Reserve",
      "OVR": 88,
      "Age": 20,
      "Nationality": "Northern Ireland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 2,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 23566,
      "Morale": 86,
      "Form": 87,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P030",
      "TeamID": "T03",
      "Name": "Callum Griffin",
      "Position": "Reserve",
      "OVR": 87,
      "Age": 35,
      "Nationality": "Scotland",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 5,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 85,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 20589,
      "Morale": 80,
      "Form": 76,
      "Injured": "No"
    },
    {
      "PlayerID": "P031",
      "TeamID": "T04",
      "Name": "Eoin Thorne",
      "Position": "Chaser",
      "OVR": 90,
      "Age": 19,
      "Nationality": "England",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 3,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 22272,
      "Morale": 72,
      "Form": 80,
      "Injured": "No"
    },
    {
      "PlayerID": "P032",
      "TeamID": "T04",
      "Name": "Bran Campbell",
      "Position": "Chaser",
      "OVR": 87,
      "Age": 23,
      "Nationality": "England",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 3,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 27051,
      "Morale": 81,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P033",
      "TeamID": "T04",
      "Name": "Alasdair Locke",
      "Position": "Chaser",
      "OVR": 84,
      "Age": 30,
      "Nationality": "Scotland",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 4,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 16831,
      "Morale": 94,
      "Form": 69,
      "Injured": "No"
    },
    {
      "PlayerID": "P034",
      "TeamID": "T04",
      "Name": "Sean Doyle",
      "Position": "Beater",
      "OVR": 90,
      "Age": 18,
      "Nationality": "England",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 1,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 87,
      "Attribute2": "BatAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 23680,
      "Morale": 98,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P035",
      "TeamID": "T04",
      "Name": "Hamish Sterling",
      "Position": "Beater",
      "OVR": 90,
      "Age": 29,
      "Nationality": "England",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 2,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 91,
      "Attribute2": "BatAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 25984,
      "Morale": 72,
      "Form": 65,
      "Injured": "No"
    },
    {
      "PlayerID": "P036",
      "TeamID": "T04",
      "Name": "Edwin Murphy",
      "Position": "Keeper",
      "OVR": 91,
      "Age": 20,
      "Nationality": "England",
      "Value(G)": 13448,
      "Salary(G/week)": 112,
      "ContractYears": 3,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 89,
      "Attribute2": "Saving",
      "Value2": 90,
      "ReleaseClause(G)": 34426,
      "Morale": 71,
      "Form": 74,
      "Injured": "No"
    },
    {
      "PlayerID": "P037",
      "TeamID": "T04",
      "Name": "Wyatt Doyle",
      "Position": "Seeker",
      "OVR": 84,
      "Age": 35,
      "Nationality": "England",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 4,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "Agility",
      "Value2": 87,
      "ReleaseClause(G)": 20345,
      "Morale": 80,
      "Form": 65,
      "Injured": "No"
    },
    {
      "PlayerID": "P038",
      "TeamID": "T04",
      "Name": "Finn Oakley",
      "Position": "Reserve",
      "OVR": 87,
      "Age": 29,
      "Nationality": "Scotland",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 2,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 23218,
      "Morale": 91,
      "Form": 87,
      "Injured": "No"
    },
    {
      "PlayerID": "P039",
      "TeamID": "T04",
      "Name": "Henry Morgan",
      "Position": "Reserve",
      "OVR": 88,
      "Age": 30,
      "Nationality": "England",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 2,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 89,
      "ReleaseClause(G)": 24143,
      "Morale": 88,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P040",
      "TeamID": "T04",
      "Name": "Fraser York",
      "Position": "Reserve",
      "OVR": 88,
      "Age": 36,
      "Nationality": "Scotland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 3,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 25414,
      "Morale": 98,
      "Form": 85,
      "Injured": "No"
    },
    {
      "PlayerID": "P041",
      "TeamID": "T05",
      "Name": "Zane Crawley",
      "Position": "Chaser",
      "OVR": 89,
      "Age": 31,
      "Nationality": "Wales",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 2,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 23362,
      "Morale": 78,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P042",
      "TeamID": "T05",
      "Name": "Owain Byrne",
      "Position": "Chaser",
      "OVR": 90,
      "Age": 22,
      "Nationality": "Wales",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 4,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 91,
      "Attribute2": "ShotAccuracy",
      "Value2": 91,
      "ReleaseClause(G)": 24064,
      "Morale": 89,
      "Form": 83,
      "Injured": "No"
    },
    {
      "PlayerID": "P043",
      "TeamID": "T05",
      "Name": "Callum West",
      "Position": "Chaser",
      "OVR": 82,
      "Age": 24,
      "Nationality": "Wales",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 5,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 82,
      "ReleaseClause(G)": 15892,
      "Morale": 78,
      "Form": 99,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P044",
      "TeamID": "T05",
      "Name": "Owain Vale",
      "Position": "Beater",
      "OVR": 87,
      "Age": 26,
      "Nationality": "Wales",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 4,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 90,
      "Attribute2": "BatAccuracy",
      "Value2": 89,
      "ReleaseClause(G)": 28146,
      "Morale": 83,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P045",
      "TeamID": "T05",
      "Name": "Darragh Campbell",
      "Position": "Beater",
      "OVR": 90,
      "Age": 24,
      "Nationality": "Wales",
      "Value(G)": 12800,
      "Salary(G/week)": 106,
      "ContractYears": 1,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 87,
      "Attribute2": "BatAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 31488,
      "Morale": 82,
      "Form": 79,
      "Injured": "No"
    },
    {
      "PlayerID": "P046",
      "TeamID": "T05",
      "Name": "Yorick Crawley",
      "Position": "Keeper",
      "OVR": 89,
      "Age": 20,
      "Nationality": "Wales",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 2,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 89,
      "Attribute2": "Saving",
      "Value2": 90,
      "ReleaseClause(G)": 21294,
      "Morale": 97,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P047",
      "TeamID": "T05",
      "Name": "Gareth Locke",
      "Position": "Seeker",
      "OVR": 85,
      "Age": 21,
      "Nationality": "Wales",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 4,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "Agility",
      "Value2": 87,
      "ReleaseClause(G)": 21266,
      "Morale": 79,
      "Form": 95,
      "Injured": "No"
    },
    {
      "PlayerID": "P048",
      "TeamID": "T05",
      "Name": "Aled Sterling",
      "Position": "Reserve",
      "OVR": 85,
      "Age": 25,
      "Nationality": "Wales",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 4,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 84,
      "ReleaseClause(G)": 21266,
      "Morale": 74,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P049",
      "TeamID": "T05",
      "Name": "Gavin Vale",
      "Position": "Reserve",
      "OVR": 89,
      "Age": 25,
      "Nationality": "Ireland",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 5,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 90,
      "ReleaseClause(G)": 26647,
      "Morale": 85,
      "Form": 68,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P050",
      "TeamID": "T05",
      "Name": "Oliver Fletcher",
      "Position": "Reserve",
      "OVR": 89,
      "Age": 33,
      "Nationality": "Wales",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 2,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 91,
      "Attribute2": "ShotAccuracy",
      "Value2": 90,
      "ReleaseClause(G)": 28716,
      "Morale": 94,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P051",
      "TeamID": "T06",
      "Name": "Dafydd Oakley",
      "Position": "Chaser",
      "OVR": 89,
      "Age": 35,
      "Nationality": "England",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 4,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 88,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 24457,
      "Morale": 75,
      "Form": 74,
      "Injured": "No"
    },
    {
      "PlayerID": "P052",
      "TeamID": "T06",
      "Name": "Zane Hawke",
      "Position": "Chaser",
      "OVR": 84,
      "Age": 32,
      "Nationality": "England",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 2,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 82,
      "ReleaseClause(G)": 20438,
      "Morale": 85,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P053",
      "TeamID": "T06",
      "Name": "Hamish Marlowe",
      "Position": "Chaser",
      "OVR": 86,
      "Age": 27,
      "Nationality": "England",
      "Value(G)": 10368,
      "Salary(G/week)": 86,
      "ContractYears": 5,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 83,
      "ReleaseClause(G)": 24675,
      "Morale": 70,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P054",
      "TeamID": "T06",
      "Name": "Dafydd Griffin",
      "Position": "Beater",
      "OVR": 81,
      "Age": 20,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 3,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 82,
      "Attribute2": "BatAccuracy",
      "Value2": 83,
      "ReleaseClause(G)": 13992,
      "Morale": 96,
      "Form": 96,
      "Injured": "No"
    },
    {
      "PlayerID": "P055",
      "TeamID": "T06",
      "Name": "Cedric Munro",
      "Position": "Beater",
      "OVR": 83,
      "Age": 24,
      "Nationality": "Ireland",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 3,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 82,
      "Attribute2": "BatAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 20821,
      "Morale": 78,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P056",
      "TeamID": "T06",
      "Name": "Alasdair Griffin",
      "Position": "Keeper",
      "OVR": 84,
      "Age": 33,
      "Nationality": "England",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 5,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 84,
      "Attribute2": "Saving",
      "Value2": 87,
      "ReleaseClause(G)": 21455,
      "Morale": 92,
      "Form": 66,
      "Injured": "No"
    },
    {
      "PlayerID": "P057",
      "TeamID": "T06",
      "Name": "Conor MacLeod",
      "Position": "Seeker",
      "OVR": 82,
      "Age": 24,
      "Nationality": "Scotland",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 5,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 79,
      "Attribute2": "Agility",
      "Value2": 84,
      "ReleaseClause(G)": 19988,
      "Morale": 94,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P058",
      "TeamID": "T06",
      "Name": "Cedric Blackwood",
      "Position": "Reserve",
      "OVR": 89,
      "Age": 35,
      "Nationality": "Wales",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 5,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 90,
      "ReleaseClause(G)": 29324,
      "Morale": 78,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P059",
      "TeamID": "T06",
      "Name": "Oliver Boyd",
      "Position": "Reserve",
      "OVR": 85,
      "Age": 28,
      "Nationality": "England",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 4,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 22050,
      "Morale": 100,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P060",
      "TeamID": "T06",
      "Name": "Iain McBride",
      "Position": "Reserve",
      "OVR": 82,
      "Age": 34,
      "Nationality": "England",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 3,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "ShotAccuracy",
      "Value2": 83,
      "ReleaseClause(G)": 17203,
      "Morale": 70,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P061",
      "TeamID": "T07",
      "Name": "Gareth Hawke",
      "Position": "Chaser",
      "OVR": 85,
      "Age": 22,
      "Nationality": "England",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 3,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 22246,
      "Morale": 89,
      "Form": 82,
      "Injured": "No"
    },
    {
      "PlayerID": "P062",
      "TeamID": "T07",
      "Name": "Wyatt Evans",
      "Position": "Chaser",
      "OVR": 80,
      "Age": 31,
      "Nationality": "England",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 4,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 13968,
      "Morale": 98,
      "Form": 94,
      "Injured": "No"
    },
    {
      "PlayerID": "P063",
      "TeamID": "T07",
      "Name": "Niall Crawley",
      "Position": "Chaser",
      "OVR": 83,
      "Age": 30,
      "Nationality": "Ireland",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 4,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 82,
      "ReleaseClause(G)": 14810,
      "Morale": 82,
      "Form": 66,
      "Injured": "No"
    },
    {
      "PlayerID": "P064",
      "TeamID": "T07",
      "Name": "Vaughn Boyd",
      "Position": "Beater",
      "OVR": 83,
      "Age": 36,
      "Nationality": "England",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 3,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 81,
      "Attribute2": "BatAccuracy",
      "Value2": 85,
      "ReleaseClause(G)": 19340,
      "Morale": 81,
      "Form": 79,
      "Injured": "No"
    },
    {
      "PlayerID": "P065",
      "TeamID": "T07",
      "Name": "Gareth Ashford",
      "Position": "Beater",
      "OVR": 88,
      "Age": 32,
      "Nationality": "England",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 4,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 85,
      "Attribute2": "BatAccuracy",
      "Value2": 85,
      "ReleaseClause(G)": 27378,
      "Morale": 72,
      "Form": 67,
      "Injured": "No"
    },
    {
      "PlayerID": "P066",
      "TeamID": "T07",
      "Name": "Bren MacLeod",
      "Position": "Keeper",
      "OVR": 81,
      "Age": 35,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 2,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 78,
      "Attribute2": "Saving",
      "Value2": 83,
      "ReleaseClause(G)": 15914,
      "Morale": 90,
      "Form": 68,
      "Injured": "No"
    },
    {
      "PlayerID": "P067",
      "TeamID": "T07",
      "Name": "Ulric Quinn",
      "Position": "Seeker",
      "OVR": 84,
      "Age": 26,
      "Nationality": "England",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 1,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "Agility",
      "Value2": 84,
      "ReleaseClause(G)": 17386,
      "Morale": 91,
      "Form": 95,
      "Injured": "No"
    },
    {
      "PlayerID": "P068",
      "TeamID": "T07",
      "Name": "Silas Ross",
      "Position": "Reserve",
      "OVR": 81,
      "Age": 27,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 5,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 81,
      "Attribute2": "ShotAccuracy",
      "Value2": 78,
      "ReleaseClause(G)": 13377,
      "Morale": 85,
      "Form": 97,
      "Injured": "No"
    },
    {
      "PlayerID": "P069",
      "TeamID": "T07",
      "Name": "Tristan Ross",
      "Position": "Reserve",
      "OVR": 84,
      "Age": 28,
      "Nationality": "England",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 1,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 85,
      "Attribute2": "ShotAccuracy",
      "Value2": 85,
      "ReleaseClause(G)": 21732,
      "Morale": 85,
      "Form": 94,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P070",
      "TeamID": "T07",
      "Name": "Gareth Vale",
      "Position": "Reserve",
      "OVR": 83,
      "Age": 24,
      "Nationality": "England",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 1,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 81,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 19863,
      "Morale": 97,
      "Form": 92,
      "Injured": "No"
    },
    {
      "PlayerID": "P071",
      "TeamID": "T08",
      "Name": "Callum Kelly",
      "Position": "Chaser",
      "OVR": 79,
      "Age": 29,
      "Nationality": "Wales",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 3,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 77,
      "Attribute2": "ShotAccuracy",
      "Value2": 78,
      "ReleaseClause(G)": 15272,
      "Morale": 76,
      "Form": 69,
      "Injured": "No"
    },
    {
      "PlayerID": "P072",
      "TeamID": "T08",
      "Name": "Wyatt Morgan",
      "Position": "Chaser",
      "OVR": 81,
      "Age": 26,
      "Nationality": "Wales",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 1,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 79,
      "Attribute2": "ShotAccuracy",
      "Value2": 83,
      "ReleaseClause(G)": 16067,
      "Morale": 87,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P073",
      "TeamID": "T08",
      "Name": "Zane Dawson",
      "Position": "Chaser",
      "OVR": 86,
      "Age": 35,
      "Nationality": "Wales",
      "Value(G)": 10368,
      "Salary(G/week)": 86,
      "ContractYears": 3,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 89,
      "ReleaseClause(G)": 24468,
      "Morale": 84,
      "Form": 85,
      "Injured": "No"
    },
    {
      "PlayerID": "P074",
      "TeamID": "T08",
      "Name": "Callum Campbell",
      "Position": "Beater",
      "OVR": 81,
      "Age": 29,
      "Nationality": "Wales",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 5,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 79,
      "Attribute2": "BatAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 17528,
      "Morale": 87,
      "Form": 77,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P075",
      "TeamID": "T08",
      "Name": "Alasdair Fletcher",
      "Position": "Beater",
      "OVR": 84,
      "Age": 36,
      "Nationality": "Wales",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 5,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 84,
      "Attribute2": "BatAccuracy",
      "Value2": 87,
      "ReleaseClause(G)": 19328,
      "Morale": 87,
      "Form": 84,
      "Injured": "No"
    },
    {
      "PlayerID": "P076",
      "TeamID": "T08",
      "Name": "Vaughn Hawke",
      "Position": "Keeper",
      "OVR": 82,
      "Age": 28,
      "Nationality": "Wales",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 4,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 83,
      "Attribute2": "Saving",
      "Value2": 85,
      "ReleaseClause(G)": 19906,
      "Morale": 99,
      "Form": 78,
      "Injured": "No"
    },
    {
      "PlayerID": "P077",
      "TeamID": "T08",
      "Name": "Owain Munro",
      "Position": "Seeker",
      "OVR": 87,
      "Age": 31,
      "Nationality": "England",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 5,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 87,
      "Attribute2": "Agility",
      "Value2": 88,
      "ReleaseClause(G)": 28146,
      "Morale": 97,
      "Form": 72,
      "Injured": "No"
    },
    {
      "PlayerID": "P078",
      "TeamID": "T08",
      "Name": "Owain Morgan",
      "Position": "Reserve",
      "OVR": 83,
      "Age": 21,
      "Nationality": "Ireland",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 1,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 17772,
      "Morale": 91,
      "Form": 98,
      "Injured": "No"
    },
    {
      "PlayerID": "P079",
      "TeamID": "T08",
      "Name": "Aled Byrne",
      "Position": "Reserve",
      "OVR": 83,
      "Age": 29,
      "Nationality": "Ireland",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 3,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 81,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 14897,
      "Morale": 90,
      "Form": 77,
      "Injured": "No"
    },
    {
      "PlayerID": "P080",
      "TeamID": "T08",
      "Name": "Callum Ross",
      "Position": "Reserve",
      "OVR": 82,
      "Age": 32,
      "Nationality": "Wales",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 2,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 80,
      "Attribute2": "ShotAccuracy",
      "Value2": 82,
      "ReleaseClause(G)": 20234,
      "Morale": 74,
      "Form": 75,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P081",
      "TeamID": "T09",
      "Name": "Alasdair Byrne",
      "Position": "Chaser",
      "OVR": 83,
      "Age": 27,
      "Nationality": "England",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 5,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 17162,
      "Morale": 81,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P082",
      "TeamID": "T09",
      "Name": "Gavin Crawley",
      "Position": "Chaser",
      "OVR": 85,
      "Age": 30,
      "Nationality": "England",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 5,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 88,
      "ReleaseClause(G)": 22148,
      "Morale": 96,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P083",
      "TeamID": "T09",
      "Name": "Ansel Davies",
      "Position": "Chaser",
      "OVR": 80,
      "Age": 26,
      "Nationality": "Northern Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 3,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 80,
      "Attribute2": "ShotAccuracy",
      "Value2": 77,
      "ReleaseClause(G)": 13320,
      "Morale": 98,
      "Form": 67,
      "Injured": "No"
    },
    {
      "PlayerID": "P084",
      "TeamID": "T09",
      "Name": "Gavin Locke",
      "Position": "Beater",
      "OVR": 81,
      "Age": 32,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 5,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 81,
      "Attribute2": "BatAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 13454,
      "Morale": 96,
      "Form": 71,
      "Injured": "No"
    },
    {
      "PlayerID": "P085",
      "TeamID": "T09",
      "Name": "Bren Price",
      "Position": "Beater",
      "OVR": 83,
      "Age": 34,
      "Nationality": "England",
      "Value(G)": 8712,
      "Salary(G/week)": 72,
      "ContractYears": 1,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 80,
      "Attribute2": "BatAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 19602,
      "Morale": 91,
      "Form": 73,
      "Injured": "No"
    },
    {
      "PlayerID": "P086",
      "TeamID": "T09",
      "Name": "Cedric Oakley",
      "Position": "Keeper",
      "OVR": 80,
      "Age": 25,
      "Nationality": "Northern Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 2,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 80,
      "Attribute2": "Saving",
      "Value2": 78,
      "ReleaseClause(G)": 16560,
      "Morale": 82,
      "Form": 97,
      "Injured": "No"
    },
    {
      "PlayerID": "P087",
      "TeamID": "T09",
      "Name": "Oliver Dawson",
      "Position": "Seeker",
      "OVR": 80,
      "Age": 33,
      "Nationality": "England",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 2,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 79,
      "Attribute2": "Agility",
      "Value2": 82,
      "ReleaseClause(G)": 15408,
      "Morale": 96,
      "Form": 90,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P088",
      "TeamID": "T09",
      "Name": "Xander Griffin",
      "Position": "Reserve",
      "OVR": 82,
      "Age": 32,
      "Nationality": "England",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 5,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 85,
      "Attribute2": "ShotAccuracy",
      "Value2": 83,
      "ReleaseClause(G)": 20807,
      "Morale": 78,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P089",
      "TeamID": "T09",
      "Name": "Dorian Ross",
      "Position": "Reserve",
      "OVR": 82,
      "Age": 26,
      "Nationality": "England",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 4,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 84,
      "ReleaseClause(G)": 15155,
      "Morale": 74,
      "Form": 76,
      "Injured": "No"
    },
    {
      "PlayerID": "P090",
      "TeamID": "T09",
      "Name": "Hamish Wilson",
      "Position": "Reserve",
      "OVR": 79,
      "Age": 21,
      "Nationality": "England",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 2,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 81,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 13119,
      "Morale": 96,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P091",
      "TeamID": "T10",
      "Name": "Sean Evans",
      "Position": "Chaser",
      "OVR": 82,
      "Age": 30,
      "Nationality": "England",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 2,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 18759,
      "Morale": 78,
      "Form": 94,
      "Injured": "No"
    },
    {
      "PlayerID": "P092",
      "TeamID": "T10",
      "Name": "Alasdair Grant",
      "Position": "Chaser",
      "OVR": 81,
      "Age": 28,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 4,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 81,
      "ReleaseClause(G)": 19911,
      "Morale": 100,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P093",
      "TeamID": "T10",
      "Name": "Vaughn Davies",
      "Position": "Chaser",
      "OVR": 80,
      "Age": 35,
      "Nationality": "Northern Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 3,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 80,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 12744,
      "Morale": 94,
      "Form": 98,
      "Injured": "No"
    },
    {
      "PlayerID": "P094",
      "TeamID": "T10",
      "Name": "Cedric Thorne",
      "Position": "Beater",
      "OVR": 80,
      "Age": 25,
      "Nationality": "Wales",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 3,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 80,
      "Attribute2": "BatAccuracy",
      "Value2": 77,
      "ReleaseClause(G)": 15552,
      "Morale": 80,
      "Form": 85,
      "Injured": "No"
    },
    {
      "PlayerID": "P095",
      "TeamID": "T10",
      "Name": "Wyatt Lloyd",
      "Position": "Beater",
      "OVR": 85,
      "Age": 26,
      "Nationality": "England",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 2,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 87,
      "Attribute2": "BatAccuracy",
      "Value2": 85,
      "ReleaseClause(G)": 19796,
      "Morale": 94,
      "Form": 88,
      "Injured": "No"
    },
    {
      "PlayerID": "P096",
      "TeamID": "T10",
      "Name": "Arthur Doyle",
      "Position": "Keeper",
      "OVR": 80,
      "Age": 35,
      "Nationality": "England",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 1,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 82,
      "Attribute2": "Saving",
      "Value2": 80,
      "ReleaseClause(G)": 16488,
      "Morale": 78,
      "Form": 84,
      "Injured": "No"
    },
    {
      "PlayerID": "P097",
      "TeamID": "T10",
      "Name": "Ulric Davies",
      "Position": "Seeker",
      "OVR": 79,
      "Age": 21,
      "Nationality": "England",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 5,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "Agility",
      "Value2": 81,
      "ReleaseClause(G)": 15878,
      "Morale": 77,
      "Form": 87,
      "Injured": "No"
    },
    {
      "PlayerID": "P098",
      "TeamID": "T10",
      "Name": "Arthur Locke",
      "Position": "Reserve",
      "OVR": 81,
      "Age": 35,
      "Nationality": "England",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 3,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 14145,
      "Morale": 81,
      "Form": 67,
      "Injured": "No"
    },
    {
      "PlayerID": "P099",
      "TeamID": "T10",
      "Name": "Callum Marlowe",
      "Position": "Reserve",
      "OVR": 79,
      "Age": 34,
      "Nationality": "England",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 4,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "ShotAccuracy",
      "Value2": 78,
      "ReleaseClause(G)": 13119,
      "Morale": 97,
      "Form": 97,
      "Injured": "No"
    },
    {
      "PlayerID": "P100",
      "TeamID": "T10",
      "Name": "Ulric MacKay",
      "Position": "Reserve",
      "OVR": 77,
      "Age": 21,
      "Nationality": "Scotland",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 1,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 78,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 12305,
      "Morale": 88,
      "Form": 88,
      "Injured": "No"
    },
    {
      "PlayerID": "P101",
      "TeamID": "T11",
      "Name": "Eoin Vale",
      "Position": "Chaser",
      "OVR": 84,
      "Age": 23,
      "Nationality": "Ireland",
      "Value(G)": 9248,
      "Salary(G/week)": 77,
      "ContractYears": 1,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 85,
      "Attribute2": "ShotAccuracy",
      "Value2": 85,
      "ReleaseClause(G)": 18311,
      "Morale": 98,
      "Form": 67,
      "Injured": "No"
    },
    {
      "PlayerID": "P102",
      "TeamID": "T11",
      "Name": "Ulric Oakley",
      "Position": "Chaser",
      "OVR": 77,
      "Age": 19,
      "Nationality": "Ireland",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 1,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 75,
      "Attribute2": "ShotAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 14171,
      "Morale": 81,
      "Form": 73,
      "Injured": "No"
    },
    {
      "PlayerID": "P103",
      "TeamID": "T11",
      "Name": "Zane West",
      "Position": "Chaser",
      "OVR": 79,
      "Age": 25,
      "Nationality": "England",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 3,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "ShotAccuracy",
      "Value2": 82,
      "ReleaseClause(G)": 11774,
      "Morale": 86,
      "Form": 70,
      "Injured": "No"
    },
    {
      "PlayerID": "P104",
      "TeamID": "T11",
      "Name": "Kieran Campbell",
      "Position": "Beater",
      "OVR": 80,
      "Age": 28,
      "Nationality": "Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 5,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 79,
      "Attribute2": "BatAccuracy",
      "Value2": 77,
      "ReleaseClause(G)": 14184,
      "Morale": 95,
      "Form": 96,
      "Injured": "No"
    },
    {
      "PlayerID": "P105",
      "TeamID": "T11",
      "Name": "Ansel Byrne",
      "Position": "Beater",
      "OVR": 79,
      "Age": 22,
      "Nationality": "Scotland",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 2,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 81,
      "Attribute2": "BatAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 12581,
      "Morale": 92,
      "Form": 74,
      "Injured": "No"
    },
    {
      "PlayerID": "P106",
      "TeamID": "T11",
      "Name": "Liam West",
      "Position": "Keeper",
      "OVR": 79,
      "Age": 29,
      "Nationality": "Ireland",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 3,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 82,
      "Attribute2": "Saving",
      "Value2": 80,
      "ReleaseClause(G)": 13523,
      "Morale": 86,
      "Form": 85,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P107",
      "TeamID": "T11",
      "Name": "Sean Campbell",
      "Position": "Seeker",
      "OVR": 80,
      "Age": 21,
      "Nationality": "Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 5,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 79,
      "Attribute2": "Agility",
      "Value2": 79,
      "ReleaseClause(G)": 15624,
      "Morale": 81,
      "Form": 78,
      "Injured": "No"
    },
    {
      "PlayerID": "P108",
      "TeamID": "T11",
      "Name": "Xander Fletcher",
      "Position": "Reserve",
      "OVR": 77,
      "Age": 27,
      "Nationality": "Wales",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 2,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 78,
      "Attribute2": "ShotAccuracy",
      "Value2": 75,
      "ReleaseClause(G)": 12538,
      "Morale": 73,
      "Form": 74,
      "Injured": "No"
    },
    {
      "PlayerID": "P109",
      "TeamID": "T11",
      "Name": "Xander Ross",
      "Position": "Reserve",
      "OVR": 79,
      "Age": 23,
      "Nationality": "England",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 3,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 81,
      "Attribute2": "ShotAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 16820,
      "Morale": 93,
      "Form": 94,
      "Injured": "No"
    },
    {
      "PlayerID": "P110",
      "TeamID": "T11",
      "Name": "Dorian Grant",
      "Position": "Reserve",
      "OVR": 81,
      "Age": 33,
      "Nationality": "Ireland",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 2,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 83,
      "Attribute2": "ShotAccuracy",
      "Value2": 80,
      "ReleaseClause(G)": 16375,
      "Morale": 92,
      "Form": 90,
      "Injured": "No"
    },
    {
      "PlayerID": "P111",
      "TeamID": "T12",
      "Name": "Gavin Griffin",
      "Position": "Chaser",
      "OVR": 79,
      "Age": 18,
      "Nationality": "Scotland",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 3,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 82,
      "Attribute2": "ShotAccuracy",
      "Value2": 77,
      "ReleaseClause(G)": 14599,
      "Morale": 76,
      "Form": 87,
      "Injured": "No"
    },
    {
      "PlayerID": "P112",
      "TeamID": "T12",
      "Name": "Zane Munro",
      "Position": "Chaser",
      "OVR": 74,
      "Age": 24,
      "Nationality": "Scotland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 1,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 72,
      "Attribute2": "ShotAccuracy",
      "Value2": 75,
      "ReleaseClause(G)": 11796,
      "Morale": 99,
      "Form": 91,
      "Injured": "No"
    },
    {
      "PlayerID": "P113",
      "TeamID": "T12",
      "Name": "Finn Davies",
      "Position": "Chaser",
      "OVR": 81,
      "Age": 36,
      "Nationality": "Ireland",
      "Value(G)": 7688,
      "Salary(G/week)": 64,
      "ContractYears": 4,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 18912,
      "Morale": 96,
      "Form": 89,
      "Injured": "No"
    },
    {
      "PlayerID": "P114",
      "TeamID": "T12",
      "Name": "Sean Sterling",
      "Position": "Beater",
      "OVR": 82,
      "Age": 21,
      "Nationality": "Scotland",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 2,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 82,
      "Attribute2": "BatAccuracy",
      "Value2": 84,
      "ReleaseClause(G)": 15155,
      "Morale": 83,
      "Form": 83,
      "Injured": "No"
    },
    {
      "PlayerID": "P115",
      "TeamID": "T12",
      "Name": "Callum Baker",
      "Position": "Beater",
      "OVR": 80,
      "Age": 21,
      "Nationality": "Ireland",
      "Value(G)": 7200,
      "Salary(G/week)": 60,
      "ContractYears": 2,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 79,
      "Attribute2": "BatAccuracy",
      "Value2": 78,
      "ReleaseClause(G)": 12672,
      "Morale": 77,
      "Form": 69,
      "Injured": "No"
    },
    {
      "PlayerID": "P116",
      "TeamID": "T12",
      "Name": "Cedric Baker",
      "Position": "Keeper",
      "OVR": 77,
      "Age": 30,
      "Nationality": "Scotland",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 5,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 80,
      "Attribute2": "Saving",
      "Value2": 74,
      "ReleaseClause(G)": 15104,
      "Morale": 81,
      "Form": 70,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P117",
      "TeamID": "T12",
      "Name": "Oliver McBride",
      "Position": "Seeker",
      "OVR": 77,
      "Age": 18,
      "Nationality": "Scotland",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 3,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 75,
      "Attribute2": "Agility",
      "Value2": 76,
      "ReleaseClause(G)": 14346,
      "Morale": 72,
      "Form": 77,
      "Injured": "No"
    },
    {
      "PlayerID": "P118",
      "TeamID": "T12",
      "Name": "Xander Lloyd",
      "Position": "Reserve",
      "OVR": 74,
      "Age": 35,
      "Nationality": "Scotland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 5,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 76,
      "Attribute2": "ShotAccuracy",
      "Value2": 73,
      "ReleaseClause(G)": 11243,
      "Morale": 79,
      "Form": 76,
      "Injured": "No"
    },
    {
      "PlayerID": "P119",
      "TeamID": "T12",
      "Name": "Gareth Morgan",
      "Position": "Reserve",
      "OVR": 76,
      "Age": 34,
      "Nationality": "Scotland",
      "Value(G)": 5408,
      "Salary(G/week)": 45,
      "ContractYears": 4,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 78,
      "Attribute2": "ShotAccuracy",
      "Value2": 74,
      "ReleaseClause(G)": 13898,
      "Morale": 81,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P120",
      "TeamID": "T12",
      "Name": "Iain Campbell",
      "Position": "Reserve",
      "OVR": 82,
      "Age": 35,
      "Nationality": "Scotland",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 5,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 80,
      "Attribute2": "ShotAccuracy",
      "Value2": 79,
      "ReleaseClause(G)": 13926,
      "Morale": 78,
      "Form": 75,
      "Injured": "No"
    },
    {
      "PlayerID": "P121",
      "TeamID": "T13",
      "Name": "Niall West",
      "Position": "Chaser",
      "OVR": 74,
      "Age": 28,
      "Nationality": "Scotland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 2,
      "Shirt": 1,
      "Attribute1": "Speed",
      "Value1": 75,
      "Attribute2": "ShotAccuracy",
      "Value2": 71,
      "ReleaseClause(G)": 11151,
      "Morale": 99,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P122",
      "TeamID": "T13",
      "Name": "Darragh Evans",
      "Position": "Chaser",
      "OVR": 73,
      "Age": 23,
      "Nationality": "Scotland",
      "Value(G)": 4232,
      "Salary(G/week)": 35,
      "ContractYears": 5,
      "Shirt": 2,
      "Attribute1": "Speed",
      "Value1": 71,
      "Attribute2": "ShotAccuracy",
      "Value2": 76,
      "ReleaseClause(G)": 10410,
      "Morale": 81,
      "Form": 91,
      "Injured": "No"
    },
    {
      "PlayerID": "P123",
      "TeamID": "T13",
      "Name": "Ansel Lloyd",
      "Position": "Chaser",
      "OVR": 76,
      "Age": 35,
      "Nationality": "Scotland",
      "Value(G)": 5408,
      "Salary(G/week)": 45,
      "ContractYears": 2,
      "Shirt": 3,
      "Attribute1": "Speed",
      "Value1": 76,
      "Attribute2": "ShotAccuracy",
      "Value2": 73,
      "ReleaseClause(G)": 12005,
      "Morale": 93,
      "Form": 100,
      "Injured": "No"
    },
    {
      "PlayerID": "P124",
      "TeamID": "T13",
      "Name": "Bran Crawley",
      "Position": "Beater",
      "OVR": 79,
      "Age": 27,
      "Nationality": "Scotland",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 4,
      "Shirt": 4,
      "Attribute1": "BatPower",
      "Value1": 78,
      "Attribute2": "BatAccuracy",
      "Value2": 76,
      "ReleaseClause(G)": 17156,
      "Morale": 77,
      "Form": 85,
      "Injured": "No"
    },
    {
      "PlayerID": "P125",
      "TeamID": "T13",
      "Name": "Sean Thorne",
      "Position": "Beater",
      "OVR": 75,
      "Age": 34,
      "Nationality": "Wales",
      "Value(G)": 5000,
      "Salary(G/week)": 41,
      "ContractYears": 2,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 76,
      "Attribute2": "BatAccuracy",
      "Value2": 72,
      "ReleaseClause(G)": 12500,
      "Morale": 99,
      "Form": 73,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P126",
      "TeamID": "T13",
      "Name": "Cedric West",
      "Position": "Keeper",
      "OVR": 73,
      "Age": 26,
      "Nationality": "Scotland",
      "Value(G)": 4232,
      "Salary(G/week)": 35,
      "ContractYears": 2,
      "Shirt": 6,
      "Attribute1": "Reflexes",
      "Value1": 71,
      "Attribute2": "Saving",
      "Value2": 74,
      "ReleaseClause(G)": 9945,
      "Morale": 82,
      "Form": 97,
      "Injured": "No"
    },
    {
      "PlayerID": "P127",
      "TeamID": "T13",
      "Name": "Edwin Locke",
      "Position": "Seeker",
      "OVR": 73,
      "Age": 21,
      "Nationality": "Scotland",
      "Value(G)": 4232,
      "Salary(G/week)": 35,
      "ContractYears": 4,
      "Shirt": 7,
      "Attribute1": "Speed",
      "Value1": 74,
      "Attribute2": "Agility",
      "Value2": 73,
      "ReleaseClause(G)": 7406,
      "Morale": 92,
      "Form": 81,
      "Injured": "No"
    },
    {
      "PlayerID": "P128",
      "TeamID": "T13",
      "Name": "Rowan Ravens",
      "Position": "Reserve",
      "OVR": 72,
      "Age": 32,
      "Nationality": "Scotland",
      "Value(G)": 3872,
      "Salary(G/week)": 32,
      "ContractYears": 2,
      "Shirt": 8,
      "Attribute1": "Speed",
      "Value1": 74,
      "Attribute2": "ShotAccuracy",
      "Value2": 71,
      "ReleaseClause(G)": 8092,
      "Morale": 94,
      "Form": 70,
      "Injured": "Yes"
    },
    {
      "PlayerID": "P129",
      "TeamID": "T13",
      "Name": "Ewan Grant",
      "Position": "Reserve",
      "OVR": 74,
      "Age": 33,
      "Nationality": "Northern Ireland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 2,
      "Shirt": 9,
      "Attribute1": "Speed",
      "Value1": 77,
      "Attribute2": "ShotAccuracy",
      "Value2": 75,
      "ReleaseClause(G)": 10967,
      "Morale": 96,
      "Form": 94,
      "Injured": "No"
    },
    {
      "PlayerID": "P130",
      "TeamID": "T13",
      "Name": "Tristan Pryce",
      "Position": "Reserve",
      "OVR": 77,
      "Age": 32,
      "Nationality": "Ireland",
      "Value(G)": 5832,
      "Salary(G/week)": 48,
      "ContractYears": 1,
      "Shirt": 10,
      "Attribute1": "Speed",
      "Value1": 79,
      "Attribute2": "ShotAccuracy",
      "Value2": 76,
      "ReleaseClause(G)": 11314,
      "Morale": 100,
      "Form": 68,
      "Injured": "No"
    }
  ],
  "TransferMarket": [
    {
      "PlayerID": "FA01",
      "TeamID": "FREE",
      "Name": "Lewis Grant",
      "Position": "Keeper",
      "OVR": 88,
      "Age": 33,
      "Nationality": "Ireland",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 0,
      "Shirt": 39,
      "Attribute1": "Reflexes",
      "Value1": 88,
      "Attribute2": "Saving",
      "Value2": 89
    },
    {
      "PlayerID": "FA02",
      "TeamID": "FREE",
      "Name": "Conor Grant",
      "Position": "Chaser",
      "OVR": 93,
      "Age": 27,
      "Nationality": "Scotland",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 0,
      "Shirt": 50,
      "Attribute1": "Speed",
      "Value1": 93,
      "Attribute2": "ShotAccuracy",
      "Value2": 96
    },
    {
      "PlayerID": "FA03",
      "TeamID": "FREE",
      "Name": "Tristan Davies",
      "Position": "Chaser",
      "OVR": 69,
      "Age": 28,
      "Nationality": "Northern Ireland",
      "Value(G)": 2888,
      "Salary(G/week)": 24,
      "ContractYears": 0,
      "Shirt": 32,
      "Attribute1": "Speed",
      "Value1": 68,
      "Attribute2": "ShotAccuracy",
      "Value2": 69
    },
    {
      "PlayerID": "FA04",
      "TeamID": "FREE",
      "Name": "Eoin Doyle",
      "Position": "Beater",
      "OVR": 74,
      "Age": 31,
      "Nationality": "Northern Ireland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 0,
      "Shirt": 5,
      "Attribute1": "BatPower",
      "Value1": 77,
      "Attribute2": "BatAccuracy",
      "Value2": 71
    },
    {
      "PlayerID": "FA05",
      "TeamID": "FREE",
      "Name": "Yorick MacLeod",
      "Position": "Keeper",
      "OVR": 74,
      "Age": 27,
      "Nationality": "Scotland",
      "Value(G)": 4608,
      "Salary(G/week)": 38,
      "ContractYears": 0,
      "Shirt": 66,
      "Attribute1": "Reflexes",
      "Value1": 77,
      "Attribute2": "Saving",
      "Value2": 75
    },
    {
      "PlayerID": "FA06",
      "TeamID": "FREE",
      "Name": "Vaughn Ashford",
      "Position": "Beater",
      "OVR": 76,
      "Age": 29,
      "Nationality": "England",
      "Value(G)": 5408,
      "Salary(G/week)": 45,
      "ContractYears": 0,
      "Shirt": 94,
      "Attribute1": "BatPower",
      "Value1": 78,
      "Attribute2": "BatAccuracy",
      "Value2": 75
    },
    {
      "PlayerID": "FA07",
      "TeamID": "FREE",
      "Name": "Alasdair North",
      "Position": "Seeker",
      "OVR": 67,
      "Age": 29,
      "Nationality": "Northern Ireland",
      "Value(G)": 2312,
      "Salary(G/week)": 19,
      "ContractYears": 0,
      "Shirt": 92,
      "Attribute1": "Speed",
      "Value1": 70,
      "Attribute2": "Agility",
      "Value2": 67
    },
    {
      "PlayerID": "FA08",
      "TeamID": "FREE",
      "Name": "Iain Griffin",
      "Position": "Seeker",
      "OVR": 93,
      "Age": 33,
      "Nationality": "England",
      "Value(G)": 14792,
      "Salary(G/week)": 123,
      "ContractYears": 0,
      "Shirt": 35,
      "Attribute1": "Speed",
      "Value1": 94,
      "Attribute2": "Agility",
      "Value2": 96
    },
    {
      "PlayerID": "FA09",
      "TeamID": "FREE",
      "Name": "Niall MacLeod",
      "Position": "Seeker",
      "OVR": 87,
      "Age": 22,
      "Nationality": "Northern Ireland",
      "Value(G)": 10952,
      "Salary(G/week)": 91,
      "ContractYears": 0,
      "Shirt": 74,
      "Attribute1": "Speed",
      "Value1": 84,
      "Attribute2": "Agility",
      "Value2": 89
    },
    {
      "PlayerID": "FA10",
      "TeamID": "FREE",
      "Name": "Bren Oakley",
      "Position": "Beater",
      "OVR": 91,
      "Age": 28,
      "Nationality": "England",
      "Value(G)": 13448,
      "Salary(G/week)": 112,
      "ContractYears": 0,
      "Shirt": 96,
      "Attribute1": "BatPower",
      "Value1": 92,
      "Attribute2": "BatAccuracy",
      "Value2": 90
    },
    {
      "PlayerID": "FA11",
      "TeamID": "FREE",
      "Name": "Niall Locke",
      "Position": "Chaser",
      "OVR": 85,
      "Age": 25,
      "Nationality": "Northern Ireland",
      "Value(G)": 9800,
      "Salary(G/week)": 81,
      "ContractYears": 0,
      "Shirt": 85,
      "Attribute1": "Speed",
      "Value1": 86,
      "Attribute2": "ShotAccuracy",
      "Value2": 82
    },
    {
      "PlayerID": "FA12",
      "TeamID": "FREE",
      "Name": "Vaughn Oakley",
      "Position": "Keeper",
      "OVR": 79,
      "Age": 19,
      "Nationality": "Ireland",
      "Value(G)": 6728,
      "Salary(G/week)": 56,
      "ContractYears": 0,
      "Shirt": 76,
      "Attribute1": "Reflexes",
      "Value1": 80,
      "Attribute2": "Saving",
      "Value2": 79
    },
    {
      "PlayerID": "FA13",
      "TeamID": "FREE",
      "Name": "Callum Ellis",
      "Position": "Beater",
      "OVR": 76,
      "Age": 34,
      "Nationality": "Wales",
      "Value(G)": 5408,
      "Salary(G/week)": 45,
      "ContractYears": 0,
      "Shirt": 66,
      "Attribute1": "BatPower",
      "Value1": 75,
      "Attribute2": "BatAccuracy",
      "Value2": 78
    },
    {
      "PlayerID": "FA14",
      "TeamID": "FREE",
      "Name": "Darragh Locke",
      "Position": "Seeker",
      "OVR": 89,
      "Age": 23,
      "Nationality": "Northern Ireland",
      "Value(G)": 12168,
      "Salary(G/week)": 101,
      "ContractYears": 0,
      "Shirt": 79,
      "Attribute1": "Speed",
      "Value1": 89,
      "Attribute2": "Agility",
      "Value2": 92
    },
    {
      "PlayerID": "FA15",
      "TeamID": "FREE",
      "Name": "Gareth Fairchild",
      "Position": "Chaser",
      "OVR": 66,
      "Age": 34,
      "Nationality": "England",
      "Value(G)": 2048,
      "Salary(G/week)": 17,
      "ContractYears": 0,
      "Shirt": 23,
      "Attribute1": "Speed",
      "Value1": 66,
      "Attribute2": "ShotAccuracy",
      "Value2": 64
    },
    {
      "PlayerID": "FA16",
      "TeamID": "FREE",
      "Name": "Cian Quinn",
      "Position": "Keeper",
      "OVR": 88,
      "Age": 19,
      "Nationality": "Wales",
      "Value(G)": 11552,
      "Salary(G/week)": 96,
      "ContractYears": 0,
      "Shirt": 97,
      "Attribute1": "Reflexes",
      "Value1": 90,
      "Attribute2": "Saving",
      "Value2": 89
    },
    {
      "PlayerID": "FA17",
      "TeamID": "FREE",
      "Name": "Ewan MacKay",
      "Position": "Keeper",
      "OVR": 76,
      "Age": 19,
      "Nationality": "England",
      "Value(G)": 5408,
      "Salary(G/week)": 45,
      "ContractYears": 0,
      "Shirt": 20,
      "Attribute1": "Reflexes",
      "Value1": 75,
      "Attribute2": "Saving",
      "Value2": 75
    },
    {
      "PlayerID": "FA18",
      "TeamID": "FREE",
      "Name": "Bran MacKay",
      "Position": "Chaser",
      "OVR": 71,
      "Age": 18,
      "Nationality": "Scotland",
      "Value(G)": 3528,
      "Salary(G/week)": 29,
      "ContractYears": 0,
      "Shirt": 97,
      "Attribute1": "Speed",
      "Value1": 69,
      "Attribute2": "ShotAccuracy",
      "Value2": 71
    },
    {
      "PlayerID": "FA19",
      "TeamID": "FREE",
      "Name": "Cian Thorne",
      "Position": "Beater",
      "OVR": 82,
      "Age": 30,
      "Nationality": "Wales",
      "Value(G)": 8192,
      "Salary(G/week)": 68,
      "ContractYears": 0,
      "Shirt": 70,
      "Attribute1": "BatPower",
      "Value1": 84,
      "Attribute2": "BatAccuracy",
      "Value2": 80
    },
    {
      "PlayerID": "FA20",
      "TeamID": "FREE",
      "Name": "Dorian Baker",
      "Position": "Beater",
      "OVR": 70,
      "Age": 26,
      "Nationality": "Wales",
      "Value(G)": 3200,
      "Salary(G/week)": 26,
      "ContractYears": 0,
      "Shirt": 14,
      "Attribute1": "BatPower",
      "Value1": 67,
      "Attribute2": "BatAccuracy",
      "Value2": 70
    }
  ]
};
